# Extract Finland Iran-background data from Statistics Finland (StatFin)
# PX-Web API. Replaces the prior Eurostat-only extract: StatFin publishes
# the 2nd-generation count by background country, which Eurostat does not.
#
# Run from deployment repo root:
#   Rscript R/fi_export/extract_statfin.R
#
# Inputs (cached in _data/finland/statfin/):
#   fi_iran_origin_trend.json  - 1st + 2nd gen by year, 1990-2025
#   fi_iran_age_sex_2025.json  - age × sex × origin, 2025 only
# (Generated by curl POST to pxdata.stat.fi PxWeb API; see ../_data/finland/README.md.)
#
# Output (data/finland/):
#   fi_trend.csv     - year, gen1, gen2, total
#   fi_age_2025.csv  - age_group, male, female (1st gen + 2nd gen combined)
#   fi_headline.csv  - category, year, count (total, gen1, gen2)
#
# Definitions (per StatFin "Syntyperä" / Origin):
#   Code 22 = Persons with foreign background, born abroad (1st generation)
#   Code 21 = Persons with foreign background, born in Finland (2nd generation)
#   Background country 364 = Iran.

suppressPackageStartupMessages({
  library(jsonlite)
  library(dplyr)
})

OUT_DIR <- "data/finland"
IN_DIR  <- "../_data/finland/statfin"
dir.create(OUT_DIR, showWarnings = FALSE, recursive = TRUE)

# --- 1. Trend 1990-2025 by origin ---------------------------------------------
cat("Loading trend (1st + 2nd gen, 1990-2025)...\n")
tr_json <- read_json(file.path(IN_DIR, "fi_iran_origin_trend.json"))
years    <- names(tr_json$dimension$Vuosi$category$index)
origins  <- names(tr_json$dimension$Syntyperä$category$index)
vals     <- unlist(tr_json$value)
n_years  <- length(years)
# Dim order: Syntyperä, Taustamaa, Kieli, Vuosi, Ikä, Sukupuoli, Tiedot.
# All dims except Syntyperä and Vuosi are singletons, so layout is
# Origin × Year (Origin slowest).
g1 <- vals[1:n_years]                              # origin 22 (1st gen)
g2 <- vals[(n_years + 1):(2 * n_years)]            # origin 21 (2nd gen)
trend <- tibble(year = as.integer(years),
                gen1 = g1, gen2 = g2,
                total = g1 + g2) %>%
  arrange(year)
write.csv(trend, file.path(OUT_DIR, "fi_trend.csv"), row.names = FALSE)
cat(sprintf("Years %d-%d; 2025 totals: 1st gen %s, 2nd gen %s, total %s\n",
            min(trend$year), max(trend$year),
            format(tail(trend$gen1, 1), big.mark = ","),
            format(tail(trend$gen2, 1), big.mark = ","),
            format(tail(trend$total, 1), big.mark = ",")))

# --- 2. Age × sex × origin for 2025 ------------------------------------------
cat("\nLoading age × sex 2025...\n")
as_json <- read_json(file.path(IN_DIR, "fi_iran_age_sex_2025.json"))
age_codes <- names(as_json$dimension$Ikä$category$index)
sex_codes <- names(as_json$dimension$Sukupuoli$category$index)
origin_codes_as <- names(as_json$dimension$Syntyperä$category$index)
age_labels <- unlist(as_json$dimension$Ikä$category$label)
vals_as <- unlist(as_json$value)

n_a <- length(age_codes); n_s <- length(sex_codes); n_o <- length(origin_codes_as)
# Dim order: Syntyperä, Taustamaa, Kieli, Vuosi, Ikä, Sukupuoli, Tiedot
# Layout: Origin(2) × 1 × 1 × 1 × Age(n_a) × Sex(n_s) × 1
# Index: oi*n_a*n_s + ai*n_s + si

# Build long table dropping SSS rows (which are subtotals).
rows <- list()
for (oi in seq_along(origin_codes_as)) {
  for (ai in seq_along(age_codes)) {
    if (age_codes[ai] == "SSS") next
    for (si in seq_along(sex_codes)) {
      idx <- (oi - 1) * n_a * n_s + (ai - 1) * n_s + si
      rows[[length(rows) + 1L]] <- tibble(
        origin = origin_codes_as[oi],
        age_code = age_codes[ai],
        age = as.integer(sub("100-", "100", age_codes[ai])),
        sex = sex_codes[si],
        count = vals_as[idx]
      )
    }
  }
}
long <- bind_rows(rows)

# Bin to 5-year age groups for chart legibility
bin_age <- function(a) {
  cut(a, breaks = c(seq(0, 85, by = 5), Inf),
      right = FALSE,
      labels = c("0-4","5-9","10-14","15-19","20-24","25-29","30-34","35-39",
                 "40-44","45-49","50-54","55-59","60-64","65-69","70-74",
                 "75-79","80-84","85+"))
}
age_tbl <- long %>%
  mutate(age_group = bin_age(age),
         sex_label = ifelse(sex == "1", "male", "female")) %>%
  group_by(age_group, sex_label) %>%
  summarize(count = sum(count), .groups = "drop") %>%
  tidyr::pivot_wider(names_from = sex_label, values_from = count, values_fill = 0) %>%
  arrange(age_group)
write.csv(age_tbl, file.path(OUT_DIR, "fi_age_2025.csv"), row.names = FALSE)
cat("Age × sex 2025 (combined 1st + 2nd gen):\n")
print(age_tbl)

# --- 3. Region breakdown (Iran-born by maakunta, 2025) -----------------------
# Note: this uses table 11rp (country of birth × region), so it counts only
# Iran-born (1st gen). 2nd-gen by region isn't separately published by StatFin
# in a single table; the map purposely shows 1st-gen geography.
reg_json <- read_json(file.path(IN_DIR, "fi_iran_region_2025.json"))
reg_codes  <- names(reg_json$dimension$Maakunta$category$index)
reg_labels <- unlist(reg_json$dimension$Maakunta$category$label)
reg_vals   <- unlist(reg_json$value)
region_tbl <- tibble(code = reg_codes, name = reg_labels, count = reg_vals) %>%
  # Keep only individual maakunta (MK*), drop aggregates SSS, MA1, MA2
  filter(grepl("^MK", code)) %>%
  # GeoJSON uses 2-digit maakunta codes like "01", "02"; strip MK prefix.
  mutate(geo_code = sub("^MK", "", code),
         # Trim leading "MK01 " from labels
         name = sub("^MK\\d+ ", "", name)) %>%
  arrange(desc(count))
write.csv(region_tbl, file.path(OUT_DIR, "fi_regions.csv"), row.names = FALSE)
cat("\nRegions (top 5):\n")
print(head(region_tbl, 5))

# --- 4. Headline (latest year) ------------------------------------------------
latest <- tail(trend, 1)
headline <- tibble(
  category = c("total", "gen1", "gen2"),
  year     = latest$year,
  count    = c(latest$total, latest$gen1, latest$gen2)
)
write.csv(headline, file.path(OUT_DIR, "fi_headline.csv"), row.names = FALSE)
cat(sprintf("\nFinland: %s Iranian-origin (%s 1st gen + %s 2nd gen), %d\n",
            format(latest$total, big.mark = ","),
            format(latest$gen1, big.mark = ","),
            format(latest$gen2, big.mark = ","),
            latest$year))
