# Europe overview page — pan-European Iran-born comparison.
#
# Consumes:
#   data/europe/iran_born_combined.csv  (generated by R/europe_export/build_iran_born_combined.R)
#
# Produces:
#   docs/pages/eu-overview.html
#
# Two charts on one page:
#   1. Bar chart — Iran-born by country, latest available year per country
#   2. Time series — Iran-born trajectory 1998-2025 for countries with
#      continuous Eurostat coverage
#
# Data is harmonized to "Iran-born" (population by country of birth) across
# all sources. Eurostat's migr_pop3ctb table is used for most European
# countries; Germany uses Mikrozensus 2024 because Eurostat doesn't publish
# Iran-born for Germany; UK uses ONS Census 2021 because the UK is not in
# Eurostat's reporting set post-Brexit.
#
# Run from the deployment repo root:
#   Rscript R/build_europe.R

suppressPackageStartupMessages({
  library(plotly)
  library(jsonlite)
  library(dplyr)
})

# ---------- PLOT HELPERS (duplicated from build_germany.R pattern) --------
# Strip internal plotly classes that jsonlite can't dispatch on
# (e.g. choropleth traces get c("plotly_colorbar", "zcolor") attached).
unclass_deep <- function(x) {
  if (is.list(x)) {
    class(x) <- NULL
    x[] <- lapply(x, unclass_deep)
  } else if (is.numeric(x) || is.integer(x) || is.logical(x) || is.character(x)) {
    class(x) <- NULL
  }
  x
}
plotly_to_json <- function(plot_obj) {
  b <- plotly_build(plot_obj)$x
  b$data   <- unclass_deep(b$data)
  b$layout <- unclass_deep(b$layout)
  list(
    data   = toJSON(b$data, auto_unbox = TRUE, null = "null", na = "null"),
    layout = toJSON(b$layout, auto_unbox = TRUE, null = "null", na = "null"),
    config = toJSON(list(responsive = TRUE, displayModeBar = FALSE), auto_unbox = TRUE)
  )
}

plotly_div <- function(id, json, height = "500px", source = NULL, legend_html = NULL, highlight_hover = FALSE) {
  init_js <- sprintf('var c=Object.assign(%s,{responsive:true,scrollZoom:"geo+mapbox"});var l=%s;if(window.innerWidth<900){l.dragmode=false;}Plotly.newPlot("%s",%s,l,c);',
    json$config, json$layout, id, json$data)
  if (highlight_hover) {
    init_js <- paste0(init_js, sprintf('
var el=document.getElementById("%s");
function hlOn(lg){
  el.data.forEach(function(t,i){
    Plotly.restyle(el,{opacity:t.legendgroup===lg?1:0.15,"marker.line.width":t.legendgroup===lg?3:0,"marker.line.color":"#000"},[i]);
  });
  var wrap=el.closest(".chart-card");
  if(wrap){wrap.querySelectorAll("[data-lg]").forEach(function(s){s.style.opacity=s.getAttribute("data-lg")===lg?1:0.3;});}
}
function hlOff(){
  el.data.forEach(function(t,i){Plotly.restyle(el,{opacity:1,"marker.line.width":0},[i]);});
  var wrap=el.closest(".chart-card");
  if(wrap){wrap.querySelectorAll("[data-lg]").forEach(function(s){s.style.opacity=1;});}
}
el.__hlOn=hlOn;el.__hlOff=hlOff;
el.on("plotly_hover",function(d){hlOn(d.points[0].data.legendgroup);});
el.on("plotly_unhover",hlOff);
var _lastLg=null;
el.on("plotly_click",function(d){var lg=d.points[0].data.legendgroup;if(_lastLg===lg){hlOff();_lastLg=null;}else{hlOn(lg);_lastLg=lg;}});', id))
  }
  chart <- sprintf('<div id="%s" style="width:100%%;height:%s;touch-action:pan-y;"></div>\n<script>(function(){%s})();</script>',
    id, height, init_js)
  if (!is.null(legend_html)) chart <- paste0(chart, '\n', legend_html)
  if (!is.null(source)) chart <- paste0(chart, sprintf('\n<p style="font-size:11px; color:#666; text-align:right; margin:4px 0 0 0; padding-right:2px;">%s</p>', source))
  chart
}

make_html_legend <- function(colors, labels = names(colors), break_after = NULL) {
  items <- mapply(function(col, lab) {
    html_lab <- gsub("&", "&amp;", lab)
    sprintf('<span data-lg="%s" style="display:inline-flex; align-items:center; gap:4px; cursor:pointer; transition:opacity 0.2s;" onmouseenter="var el=this.closest(\'.chart-card\').querySelector(\'.js-plotly-plot\');if(el&&el.__hlOn)el.__hlOn(this.getAttribute(\'data-lg\'));" onmouseleave="var el=this.closest(\'.chart-card\').querySelector(\'.js-plotly-plot\');if(el&&el.__hlOff)el.__hlOff();"><span style="width:12px; height:12px; background:%s; border-radius:2px; display:inline-block;"></span> %s</span>',
      lab, col, html_lab)
  }, colors, labels, SIMPLIFY = TRUE)
  sprintf('<div style="display:flex; justify-content:center; flex-wrap:wrap; gap:6px 14px; font-size:12px; color:#444; margin:6px 0 2px; line-height:2;">%s</div>',
    paste(items, collapse = ""))
}

iframe_resize_script <- '
<script>
function reportHeight() {
  if (window.parent !== window) {
    window.parent.postMessage({ type: "iframeHeight", height: document.body.scrollHeight + 20 }, "*");
  }
}
function resizeAllPlots() {
  document.querySelectorAll(".js-plotly-plot").forEach(function(p) {
    if (window.Plotly) Plotly.Plots.resize(p);
  });
  reportHeight();
}
window.addEventListener("load", function(){ setTimeout(resizeAllPlots, 300); });
window.addEventListener("resize", function(){ setTimeout(resizeAllPlots, 150); });
if (window.ResizeObserver) {
  var ro = new ResizeObserver(function(entries) {
    entries.forEach(function(e) {
      var plot = e.target.querySelector(".js-plotly-plot") || (e.target.classList.contains("js-plotly-plot") ? e.target : null);
      if (plot && window.Plotly) Plotly.Plots.resize(plot);
    });
    reportHeight();
  });
  window.addEventListener("load", function() {
    setTimeout(function() {
      document.querySelectorAll(".js-plotly-plot").forEach(function(p) {
        ro.observe(p.parentElement || p);
      });
    }, 500);
  });
}
new MutationObserver(reportHeight).observe(document.body, { childList: true, subtree: true });
</script>'

page_template <- function(title, body_html, extra_head = "") {
  paste0('<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>', title, '</title>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&display=swap" rel="stylesheet">
<script src="lib/plotly-3.4.0.min.js"></script>
<style>
* { margin:0; padding:0; box-sizing:border-box; }
body { font-family:"Montserrat",sans-serif; background:#fafafa; color:#333; padding:15px 40px; max-width:100%; overflow-x:hidden; }
.text-row { display:grid; grid-template-columns:1fr 1fr; gap:20px; margin-bottom:20px; }
.text-card { background:white; border-radius:8px; padding:20px; text-align:center;
  font-size:15px; line-height:1.6; border:1px solid #e0e0e0; }
.chart-row { display:grid; grid-template-columns:1fr; gap:20px; margin-bottom:20px; align-items:stretch; }
.chart-card { background:white; border-radius:8px; padding:16px; border:1px solid #e0e0e0; margin-bottom:20px; overflow:hidden; min-width:0; }
.section-title { font-size:16px; font-weight:600; text-align:center; margin:16px 0 8px; }
.headline { background:white; border-radius:8px; padding:30px; text-align:center; border:1px solid #e0e0e0; margin-bottom:20px; }
.headline .number { font-size:48px; font-weight:700; color:#1a4e72; line-height:1.1; }
.headline .label { font-size:14px; color:#666; margin-top:6px; }
@media (max-width:900px) {
  body { padding:10px 15px; }
  .text-row, .chart-row { grid-template-columns:1fr !important; }
  .headline .number { font-size:36px; }
  .headline { padding:20px 15px; }
  .section-title { font-size:14px; }
}
@media (max-width:480px) {
  body { padding:8px 10px; }
  .text-card { font-size:13px; padding:14px; }
  .headline .number { font-size:28px; }
  .chart-card { padding:10px; }
}
</style>
', extra_head, '
</head>
<body>
', body_html, '
', iframe_resize_script, '
</body>
</html>')
}

# ---------- DATA ----------------------------------------------------------
cat("Building Europe overview page...\n")

combined <- read.csv("data/europe/iran_born_combined.csv", stringsAsFactors = FALSE)

# ISO-3 codes for plotly's built-in country boundaries
iso3_map <- c(
  AT = "AUT", BE = "BEL", CH = "CHE", DE = "DEU", DK = "DNK",
  ES = "ESP", FR = "FRA", IT = "ITA", NL = "NLD", NO = "NOR",
  SE = "SWE", UK = "GBR"
)

# Latest year per country
latest <- combined %>%
  group_by(geo, country) %>%
  slice_max(year, n = 1) %>%
  ungroup() %>%
  arrange(desc(value)) %>%
  mutate(iso3 = iso3_map[geo])

total_iran_born <- sum(latest$value)

# ---------- CHART 1: Europe choropleth map (top-right) -------------------
# Uses plotly's built-in country boundaries — no GeoJSON needed.
# scope="europe" auto-frames the viewport to Europe. Discrete bins avoid
# plotly_build's continuous-colorscale zcolor serialization issue.
latest$map_bin <- cut(latest$value,
  breaks = c(0, 20000, 35000, 70000, 120000, Inf),
  labels = 1:5, include.lowest = TRUE) %>% as.integer()
bin_labels <- c(
  "1" = "Under 20,000",
  "2" = "20,000 – 35,000",
  "3" = "35,000 – 70,000",
  "4" = "70,000 – 120,000",
  "5" = "120,000 or more"
)
bin_colors <- list(
  c(0,   "#c6dbef"),
  c(0.2, "#9ecae1"),
  c(0.4, "#6baed6"),
  c(0.6, "#2171b5"),
  c(0.8, "#08519c"),
  c(1.0, "#08306b")
)

p_map <- plot_ly(type = "choropleth",
    locations = latest$iso3,
    z = latest$map_bin,
    text = sprintf("<b>%s</b><br>%s Iran-born residents<br>Most recent year: %d",
      latest$country, format(latest$value, big.mark = ","), latest$year),
    hoverinfo = "text",
    colorscale = bin_colors,
    zmin = 0, zmax = 5,
    showscale = FALSE,
    marker = list(line = list(color = "white", width = 0.8))
  ) %>%
  layout(
    geo = list(
      scope = "europe",
      showframe = FALSE,
      showcoastlines = TRUE,
      coastlinecolor = "#d0d0d0",
      projection = list(type = "mercator"),
      bgcolor = "white",
      landcolor = "#f5f5f5",
      showland = TRUE,
      showcountries = TRUE,
      countrycolor = "#d0d0d0",
      lataxis = list(range = c(35, 72)),
      lonaxis = list(range = c(-12, 32))
    ),
    margin = list(t = 5, b = 5, l = 0, r = 0),
    paper_bgcolor = "white"
  ) %>%
  config(displayModeBar = FALSE)

# ---------- CHART 3: Horizontal bar chart (bottom-right) -----------------
# Smaller, horizontal orientation so country names read cleanly.
# Reverse factor order so largest value is on top of the chart.
bar_df <- latest %>% arrange(value)
bar_df$country <- factor(bar_df$country, levels = bar_df$country)

p_bar <- plot_ly(
    bar_df,
    y = ~country,
    x = ~value,
    type = "bar",
    orientation = "h",
    marker = list(color = "#2774AE",
                  line = list(color = "#1a4e72", width = 0.4)),
    text = ~sprintf("<b>%s</b><br>%s Iran-born (%d)",
      country, format(value, big.mark = ","), year),
    hoverinfo = "text",
    textposition = "none"
  ) %>%
  layout(
    title = list(text = "<b>By Country, Most Recent Year</b>",
      font = list(size = 14, family = "Montserrat")),
    xaxis = list(title = "", tickformat = ",", tickfont = list(size = 10)),
    yaxis = list(title = "", tickfont = list(size = 11)),
    margin = list(t = 45, b = 30, l = 110, r = 20),
    plot_bgcolor = "white",
    paper_bgcolor = "white",
    showlegend = FALSE,
    bargap = 0.35
  ) %>%
  config(displayModeBar = FALSE)

# ---------- CHART 2: Time series (countries with continuous coverage) ----
# Show only the top 6 countries by current Iran-born — more than 6 lines
# on one chart becomes unreadable, and the smaller countries overlap.
coverage <- combined %>%
  group_by(geo, country) %>%
  summarise(n = n(), .groups = "drop")

# Eurostat-only countries with long time series (Germany and UK not in Eurostat)
eurostat_only <- latest %>%
  filter(!geo %in% c("DE", "UK")) %>%
  left_join(coverage, by = c("geo", "country")) %>%
  filter(n >= 15) %>%
  arrange(desc(value))

top6 <- head(eurostat_only, 6)
ts_data <- combined %>% filter(geo %in% top6$geo)

# Colour each country with a distinct but complementary hue; order matches
# the legend (largest current value first → strongest colour).
# Top 6 by most-recent Iran-born with n>=15 years of Eurostat coverage:
# SE, NL, AT, IT, NO, DK.
ts_colors <- c(
  "SE" = "#1a4e72",   # Sweden — dark blue
  "NL" = "#c4793a",   # Netherlands — orange
  "AT" = "#4a8c6f",   # Austria — green
  "IT" = "#8a3a8f",   # Italy — purple
  "NO" = "#5a9bd5",   # Norway — light blue
  "DK" = "#b05050"    # Denmark — muted red
)

# Direct-label each line at its rightmost point instead of using a legend —
# standard line-chart practice (see ggplot2-4.md in the r-coding skill).
# Build the line traces first, then a single text trace for the labels.
p_ts <- plot_ly()
last_points <- data.frame(
  geo = character(), country = character(),
  x = integer(), y = integer(), color = character(),
  stringsAsFactors = FALSE
)
for (g in top6$geo) {
  d <- ts_data %>% filter(geo == g) %>% arrange(year)
  p_ts <- p_ts %>% add_trace(
    data = d,
    x = ~year, y = ~value,
    type = "scatter", mode = "lines+markers",
    line = list(color = ts_colors[[g]], width = 2.5),
    marker = list(color = ts_colors[[g]], size = 5),
    text = ~sprintf("<b>%s</b> %d<br>%s Iran-born residents",
      country, year, format(value, big.mark = ",")),
    hoverinfo = "text",
    showlegend = FALSE
  )
  tail_row <- tail(d, 1)
  last_points <- rbind(last_points, data.frame(
    geo = g,
    country = tail_row$country,
    x = tail_row$year,
    y = tail_row$value,
    color = ts_colors[[g]],
    stringsAsFactors = FALSE
  ))
}

# The Netherlands / Austria lines land close together at the right edge.
# Nudge overlapping labels vertically so they don't collide. Sort by y and
# bump any label that is within MIN_GAP of the previous one.
last_points <- last_points[order(last_points$y), ]
MIN_GAP <- 3500
for (i in seq_len(nrow(last_points))[-1]) {
  gap <- last_points$y[i] - last_points$y[i - 1]
  if (gap < MIN_GAP) {
    last_points$y[i] <- last_points$y[i - 1] + MIN_GAP
  }
}

p_ts <- p_ts %>% add_trace(
  x = last_points$x,
  y = last_points$y,
  text = paste0(" ", last_points$country),
  type = "scatter",
  mode = "text",
  textposition = "middle right",
  textfont = list(
    color = last_points$color,
    size = 12,
    family = "Montserrat"
  ),
  hoverinfo = "skip",
  showlegend = FALSE,
  cliponaxis = FALSE
)

p_ts <- p_ts %>% layout(
  title = list(text = "<b>Population Over Time, 1998\u20132025</b>",
    font = list(size = 14, family = "Montserrat")),
  xaxis = list(title = "", tickfont = list(size = 10), dtick = 5,
    # Extend the x-axis past 2025 so the labels have room to render
    range = c(1997, 2033)),
  yaxis = list(title = "", tickformat = ",", tickfont = list(size = 10)),
  margin = list(t = 45, b = 30, l = 60, r = 15),
  plot_bgcolor = "white",
  paper_bgcolor = "white",
  showlegend = FALSE,
  hovermode = "closest"
) %>% config(displayModeBar = FALSE)

# ---------- ASSEMBLE PAGE -------------------------------------------------
EUROSTAT_LINK <- "<a href='https://ec.europa.eu/eurostat/databrowser/view/migr_pop3ctb/default/table' target='_blank' style='color:#2774AE;'>Eurostat</a>"
MIKRO_LINK <- "<a href='https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Bevoelkerung/Migration-Integration/Publikationen/Downloads-Migration/statistischer-bericht-migrationshintergrund-erst-2010220247005.html' target='_blank' style='color:#2774AE;'>Destatis Mikrozensus 2024</a>"
ONS_LINK <- "<a href='https://www.nomisweb.co.uk/sources/census_2021' target='_blank' style='color:#2774AE;'>ONS Census 2021</a>"

source_note <- sprintf(
  "Source: %s population by country of birth. Germany from %s. United Kingdom from %s (England, Wales, Scotland, and Northern Ireland combined).",
  EUROSTAT_LINK, MIKRO_LINK, ONS_LINK)

n_countries <- nrow(latest)

body <- paste0(
  # Top row: headline (left) + Europe choropleth map (right)
  '<div class="chart-row" style="grid-template-columns:40% 60%;">',
  '<div class="headline">',
  '<div class="label">Estimated Iran-Born Population in Europe</div>',
  '<div class="number">', format(total_iran_born, big.mark = ","), '</div>',
  '<div class="label" style="margin-top:6px; font-size:13px; color:#555;">Summed across ', n_countries, ' European countries with published data</div>',
  '<div style="margin:14px auto 0; max-width:440px; font-size:13px; color:#444; text-align:left; line-height:1.7;">',
  '<p style="margin-bottom:8px;">A person is counted if they were born in Iran and currently live in one of:</p>',
  '<ul style="padding-left:20px; margin:0; line-height:2;">',
  '<li><strong>', EUROSTAT_LINK, '</strong> <span style="color:#888;">&mdash; 9 European countries (country-of-birth tables)</span></li>',
  '<li><strong>', MIKRO_LINK, '</strong> <span style="color:#888;">&mdash; Germany</span></li>',
  '<li><strong>', ONS_LINK, '</strong> <span style="color:#888;">&mdash; United Kingdom</span></li>',
  '</ul>',
  '</div>',
  '</div>',
  '<div class="chart-card">',
  '<div class="section-title" style="margin-top:0;">Where Iran-Born Residents Live in Europe</div>',
  plotly_div("eu-map", plotly_to_json(p_map), "430px",
    source = source_note),
  '</div>',
  '</div>',

  # Bottom row: horizontal bar chart (left) + time series (right)
  '<div class="chart-row" style="grid-template-columns:40% 60%;">',
  '<div class="chart-card">',
  plotly_div("eu-bar", plotly_to_json(p_bar), "460px",
    source = "Most recent year available for each country. Hover over the map above for the exact reference year per country."),
  '</div>',
  '<div class="chart-card">',
  plotly_div("eu-timeseries", plotly_to_json(p_ts), "460px",
    source = paste0("Source: ", EUROSTAT_LINK, " \u2014 the six European countries with the longest continuous annual reporting. Germany and the United Kingdom are omitted because their data comes from one-time censuses rather than annual series.")),
  '</div>',
  '</div>'
)

dir.create("docs/pages", showWarnings = FALSE, recursive = TRUE)
writeLines(page_template("Europe: Iran-Born Overview", body), "docs/pages/eu-overview.html")
cat("  Done\n")
cat(sprintf("\nEurope overview: %s Iran-born across %d countries.\n",
            format(total_iran_born, big.mark = ","), n_countries))
