# Europe overview page — pan-European Iran-born comparison.
#
# Consumes:
#   data/europe/iran_born_combined.csv  (generated by R/europe_export/build_iran_born_combined.R)
#
# Produces:
#   docs/pages/eu-overview.html     (English, byte-identical to the committed file)
#   docs/pages/eu-overview.fa.html  (Persian, RTL + Vazirmatn + Persian digits)
#
# Two charts on one page (plus the headline + choropleth):
#   1. Bar chart — Iran-born by country, latest available year per country
#   2. Time series — Iran-born trajectory 1999-2025 for countries with
#      continuous Eurostat coverage
#
# Data is harmonized to "Iran-born" (population by country of birth) across
# all sources. Eurostat's migr_pop3ctb table is used for most European
# countries; Germany uses Mikrozensus 2025 because Eurostat doesn't publish
# Iran-born for Germany; UK uses ONS Census 2021 because the UK is not in
# Eurostat's reporting set post-Brexit.
#
# Bilingual (en + fa), following the R/build_global.R / R/build_france.R
# bespoke-page pattern: all user-facing strings come from
# R/i18n/strings_europe.R via tr(); numbers baked into Plotly go through
# fmtv()/fa_num()/htxt() so the English edition stays BYTE-IDENTICAL while the
# Persian edition renders RTL with Persian digits and the Vazirmatn face. This
# builder keeps its LOCAL page_template() (side-by-side chart-row shell) for
# English; the fa edition is that same finished shell run through fa_shell(),
# which relies on the standard anchors it already emits (<html lang="en">,
# <meta charset="utf-8">, </head>, </body>, font-family:"Montserrat",sans-serif).
#
# Run from the deployment repo root:
#   Rscript R/build_europe.R

suppressPackageStartupMessages({
  library(plotly)
  library(jsonlite)
  library(dplyr)
})

# Shared helpers: strip_internal_classes(), plotly_to_json(), plotly_div(),
# plotly_script(), make_html_legend_hover(), iframe_resize_script,
# MAPBOX_ATTRIB_HIDE_CSS.
source("R/_helpers.R")
# Persian-edition helpers: LANG, is_fa(), fa_digits(), fa_num(), bdi(), tr(),
# pj(), fa_shell().
source("R/_helpers_i18n.R")
# Europe string table (defines the STR consumed by tr(), plus EU_COUNTRY_FA).
source("R/i18n/strings_europe.R")

page_template <- function(title, body_html, extra_head = "") {
  paste0('<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>', title, '</title>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&display=swap" rel="stylesheet">
', plotly_script(body_html), '
<style>
* { margin:0; padding:0; box-sizing:border-box; }
body { font-family:"Montserrat",sans-serif; background:#fafafa; color:#333; padding:15px 40px; max-width:100%; overflow-x:hidden; }
.text-row { display:grid; grid-template-columns:1fr 1fr; gap:20px; margin-bottom:20px; }
.text-card { background:white; border-radius:8px; padding:20px; text-align:center;
  font-size:15px; line-height:1.6; border:1px solid #e0e0e0; }
.chart-row { display:grid; grid-template-columns:1fr 1fr; gap:20px; margin-bottom:20px; align-items:stretch; }
.chart-card { background:white; border-radius:8px; padding:16px; border:1px solid #e0e0e0; margin-bottom:20px; overflow:hidden; min-width:0; }
.section-title { font-size:16px; font-weight:600; text-align:center; margin:16px 0 8px; }
.headline { background:white; border-radius:8px; padding:30px; text-align:center; border:1px solid #e0e0e0; margin-bottom:20px; }
.headline .number { font-size:44px; font-weight:700; color:#1a4e72; line-height:1.1; letter-spacing:-0.02em; }
a { transition: color 0.15s; }
a:hover { color: #1a4e72 !important; text-decoration: underline; }
.headline .label { font-size:14px; color:#666; margin-top:6px; }
@media (max-width:900px) {
  body { padding:10px 15px; }
  .text-row, .chart-row { grid-template-columns:1fr !important; }
  .headline { padding:20px 15px; }
  .section-title { font-size:14px; }
}
@media (max-width:480px) {
  body { padding:8px 10px; }
  .text-card { font-size:13px; padding:14px; }
  .chart-card { padding:10px; }
}
', MAPBOX_ATTRIB_HIDE_CSS, '
</style>
', extra_head, '
</head>
<body>
', body_html, '
', iframe_resize_script, '
</body>
</html>')
}

# --- i18n formatting helpers (build_france.R pattern) -------------------------
# lnk():  in fa, isolate a Latin agency link/URL in <bdi> so the bidi algorithm
#         cannot reorder it; in en, pass through unchanged.
lnk <- function(x) if (is_fa()) bdi(x) else x

# fmtv(): vector-safe big-integer formatter. In en it is LITERALLY
#         format(x, big.mark = ",") — so it reproduces format()'s common-width
#         PADDING (leading spaces) that the committed hover text relies on. In
#         fa it Persian-digits that same string (ASCII "," thousands kept).
fmtv <- function(x) {
  s <- format(x, big.mark = ",")
  if (!is_fa()) return(s)
  fa_digits(s)
}

# htxt(): Persian-digit any stray Western digits in an assembled display string
#         (hover text, chart titles, direct labels). Identity in en. Idempotent,
#         so safe to wrap fa_num()/fmtv() output. Plain human text only.
htxt <- function(s) if (is_fa()) fa_digits(s) else s

# clab(): country display name (vectorized). en = passthrough (byte-identical);
#         fa = EU_COUNTRY_FA lookup with English fallback (never NA).
clab <- function(x) {
  if (!is_fa()) return(x)
  out <- unname(EU_COUNTRY_FA[as.character(x)])
  ifelse(is.na(out), as.character(x), out)
}

# ---------- DATA (language-independent) -----------------------------------
cat("Building Europe overview page...\n")

combined <- read.csv("data/europe/iran_born_combined.csv", stringsAsFactors = FALSE)

# ISO-3 codes for plotly's built-in country boundaries
iso3_map <- c(
  AT = "AUT", BE = "BEL", CH = "CHE", DE = "DEU", DK = "DNK",
  ES = "ESP", FI = "FIN", FR = "FRA", IT = "ITA", NL = "NLD",
  NO = "NOR", SE = "SWE", UK = "GBR",
  # Smaller Eurostat reporters added 2026-05-31 so visitors from these
  # countries can find themselves on the map.
  BG = "BGR", CZ = "CZE", EE = "EST", HU = "HUN", IS = "ISL",
  LT = "LTU", LU = "LUX", LV = "LVA", RO = "ROU", SI = "SVN", SK = "SVK"
)

# Latest year per country
latest <- combined %>%
  group_by(geo, country) %>%
  slice_max(year, n = 1) %>%
  ungroup() %>%
  arrange(desc(value)) %>%
  mutate(iso3 = iso3_map[geo])

total_iran_born <- sum(latest$value)

# Discrete map bins (avoid plotly_build's continuous-colorscale zcolor issue).
latest$map_bin <- cut(latest$value,
  breaks = c(0, 20000, 35000, 70000, 120000, Inf),
  labels = 1:5, include.lowest = TRUE) %>% as.integer()
bin_colors <- list(
  c(0,   "#c6dbef"),
  c(0.2, "#9ecae1"),
  c(0.4, "#6baed6"),
  c(0.6, "#2171b5"),
  c(0.8, "#08519c"),
  c(1.0, "#08306b")
)

# Bar chart universe: only substantial populations (>= 10,000) get a bar. The
# 11 smaller Eurostat reporters stay on the map (where finding your country is
# the point); on a 0-267k axis their bars are invisible slivers and hurt the
# ranking's legibility. Reverse factor order so the largest value is on top.
bar_df <- latest %>% filter(value >= 10000) %>% arrange(value)
bar_df$country <- factor(bar_df$country, levels = bar_df$country)

# Time-series panel: Eurostat-continuous countries plus Finland. Finland's 2025
# count (~15K) is below the top-6 cutoff by value but has 25 years of coverage;
# it sits visibly below DK and rounds out the seven-country Eurostat panel.
coverage <- combined %>%
  group_by(geo, country) %>%
  summarise(n = n(), .groups = "drop")

eurostat_only <- latest %>%
  filter(!geo %in% c("DE", "UK", "FR", "CH", "BE")) %>%
  left_join(coverage, by = c("geo", "country")) %>%
  filter(n >= 15) %>%
  arrange(desc(value))

top_eurostat <- head(eurostat_only, 7)
ts_data <- combined %>% filter(geo %in% top_eurostat$geo)

# Colour each country with a distinct but complementary hue; the seven
# Eurostat-continuous countries are SE, NL, AT, IT, NO, DK, FI.
ts_colors <- c(
  "SE" = "#1a4e72",   # Sweden — dark blue
  "NL" = "#c4793a",   # Netherlands — orange
  "AT" = "#4a8c6f",   # Austria — green
  "IT" = "#8a3a8f",   # Italy — purple
  "NO" = "#5a9bd5",   # Norway — light blue
  "DK" = "#b05050",   # Denmark — muted red
  "FI" = "#d4a943"    # Finland — gold
)

# United Kingdom: three decennial census points (2001, 2011, 2021/22). Sources:
#   2001 Census: ~42,500 Iran-born in England and Wales (ONS)
#   2011 Census:  84,735 UK total (79,985 E + 1,695 W + 2,773 S + 282 NI)
#   2021 Census: 114,432 UK total (E+W 2021 ONS + NI 2021 NISRA + Scotland 2022 NRS)
# Note: the 2021 point is labeled 2021/22 because the Scottish census was
# run a year later; the other two constituent nations are 2021.
uk_ts <- data.frame(
  year = c(2001, 2011, 2021),
  year_label = c("2001", "2011", "2021/22"),
  value = c(42494, 84735, 114432),
  country = "United Kingdom",
  stringsAsFactors = FALSE
)

# France: INSEE annual "immigré" series, 2006-2019 (2018 not published).
fr_ts <- combined %>% filter(geo == "FR", year >= 1999) %>% arrange(year)

# Switzerland: BFS register, 2010-2024 (continuous, but not Eurostat).
ch_ts <- combined %>% filter(geo == "CH") %>% arrange(year)

n_countries <- nrow(latest)
# Eurostat-attributed countries in the identification box. Switzerland is shown
# under BFS below, so it is not counted here even though its row is Eurostat.
n_eurostat_box <- sum(grepl("Eurostat", latest$source) & latest$geo != "CH")

dir.create("docs/pages", showWarnings = FALSE, recursive = TRUE)

# =============================================================================
# Bilingual build loop: en (byte-identical to committed) then fa (RTL Persian).
# LANG lives in the global env, which is where the i18n helpers read it.
# =============================================================================
for (LANG in c("en", "fa")) {

  cat(sprintf("=== Building Europe overview [%s] ===\n", LANG))

  # --- Latin source links (link text via tr(); href/style language-independent)
  EUROSTAT_LINK <- sprintf("<a href='https://ec.europa.eu/eurostat/databrowser/view/migr_pop3ctb/default/table' target='_blank' style='color:#2774AE;'>%s</a>", tr("eu_link_eurostat"))
  MIKRO_LINK <- sprintf("<a href='https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Bevoelkerung/Migration-Integration/Publikationen/Downloads-Migration/statistischer-bericht-migrationshintergrund-erst-2010220257005.html' target='_blank' style='color:#2774AE;'>%s</a>", tr("eu_link_mikro"))
  ONS_LINK <- sprintf("<a href='https://www.nomisweb.co.uk/sources/census_2021' target='_blank' style='color:#2774AE;'>%s</a>", tr("eu_link_ons"))
  NRS_LINK <- sprintf("<a href='https://www.scotlandscensus.gov.uk/' target='_blank' style='color:#2774AE;'>%s</a>", tr("eu_link_nrs"))
  NISRA_LINK <- sprintf("<a href='https://www.nisra.gov.uk/statistics/census/2021-census' target='_blank' style='color:#2774AE;'>%s</a>", tr("eu_link_nisra"))
  BFS_LINK <- sprintf("<a href='https://www.bfs.admin.ch/bfs/en/home/statistics/population.html' target='_blank' style='color:#2774AE;'>%s</a>", tr("eu_link_bfs"))
  UK_COMBINED_LINK <- sprintf(tr("eu_uk_combined"), ONS_LINK, NRS_LINK, NISRA_LINK)

  source_note <- sprintf(tr("eu_src_note"), EUROSTAT_LINK, MIKRO_LINK, UK_COMBINED_LINK)

  # ---------- CHART 1: Europe choropleth map (top-right) -------------------
  # Uses plotly's built-in country boundaries — no GeoJSON needed.
  # scope="europe" auto-frames the viewport to Europe.
  p_map <- plot_ly(type = "choropleth",
      locations = latest$iso3,
      z = latest$map_bin,
      text = htxt(sprintf(tr("eu_hover_count"),
        clab(latest$country), fmtv(latest$value),
        fa_num(latest$year, 0, big = FALSE))),
      hoverinfo = "text",
      colorscale = bin_colors,
      zmin = 0, zmax = 5,
      showscale = FALSE,
      marker = list(line = list(color = "white", width = 0.8))
    ) %>%
    layout(
      geo = list(
        scope = "europe",
        showframe = FALSE,
        showcoastlines = TRUE,
        coastlinecolor = "#d0d0d0",
        projection = list(type = "mercator"),
        bgcolor = "white",
        landcolor = "#f5f5f5",
        showland = TRUE,
        showcountries = TRUE,
        countrycolor = "#d0d0d0",
        lataxis = list(range = c(34, 74)),
        # West edge extended to -25 (was -13) so Iceland is visible on the map.
        lonaxis = list(range = c(-25, 33))
      ),
      margin = list(t = 5, b = 5, l = 0, r = 0),
      paper_bgcolor = "white"
    ) %>%
    config(displayModeBar = FALSE)

  # ---------- CHART 3: Horizontal bar chart (bottom-left) ------------------
  bar_df$hover <- htxt(sprintf(tr("eu_hover_count"),
    clab(bar_df$country), fmtv(bar_df$value),
    fa_num(bar_df$year, 0, big = FALSE)))
  # y-axis category labels: relabel the (English-ordered) factor to the display
  # language, KEEPING the descending-by-count order. On en, clab() is identity
  # so country_disp is byte-identical to the English factor; on fa the tick
  # labels become Persian (آلمان, بریتانیا, ...), matching the time-series.
  bar_df$country_disp <- factor(
    clab(as.character(bar_df$country)),
    levels = clab(levels(bar_df$country)))
  p_bar <- plot_ly(
      bar_df,
      y = ~country_disp,
      x = ~value,
      type = "bar",
      orientation = "h",
      marker = list(color = "#2774AE",
                    line = list(color = "#1a4e72", width = 0.4)),
      text = ~hover,
      hoverinfo = "text",
      textposition = "none"
    ) %>%
    layout(
      title = list(text = tr("eu_bar_title"),
        font = list(size = 14, family = "Montserrat")),
      xaxis = list(title = "", tickformat = ",", tickfont = list(size = 10)),
      yaxis = list(title = "", tickfont = list(size = 11),
                   ticks = "outside", ticklen = 8,
                   tickcolor = "rgba(0,0,0,0)"),
      margin = list(t = 45, b = 30, l = 120, r = 20),
      plot_bgcolor = "white",
      paper_bgcolor = "white",
      showlegend = FALSE,
      bargap = 0.35
    ) %>%
    config(displayModeBar = FALSE)

  # fa/RTL: mirror the horizontal ranking bar (BBC Persian convention — all
  # horizontal bars grow right-to-left from a right-hand baseline, category
  # labels on the right). Reverse the value axis, move y tick-labels to the
  # right, and swap the l/r label margins. fa-only, so EN stays byte-identical.
  # The descending-by-count y order is unaffected (x reversal doesn't touch it).
  if (is_fa()) p_bar <- p_bar %>% layout(
    xaxis = list(autorange = "reversed"),
    yaxis = list(side = "right"),
    margin = list(t = 45, b = 30, l = 20, r = 120))

  # ---------- CHART 2: Time series (countries with continuous coverage) ----
  # Direct-label each line at its rightmost point instead of using a legend.
  # Build the line traces first, then a single text trace per label.
  p_ts <- plot_ly()
  last_points <- data.frame(
    geo = character(), country = character(),
    x = integer(), y = integer(), color = character(),
    stringsAsFactors = FALSE
  )
  for (g in top_eurostat$geo) {
    d <- ts_data %>% filter(geo == g) %>% arrange(year)
    d$hover <- htxt(sprintf(tr("eu_ts_hover"),
      clab(d$country), fa_num(d$year, 0, big = FALSE), fmtv(d$value)))
    p_ts <- p_ts %>% add_trace(
      data = d,
      x = ~year, y = ~value,
      type = "scatter", mode = "lines+markers",
      line = list(color = ts_colors[[g]], width = 2.5),
      marker = list(color = ts_colors[[g]], size = 5),
      text = ~hover,
      hoverinfo = "text",
      showlegend = FALSE,
      legendgroup = g
    )
    tail_row <- tail(d, 1)
    last_points <- rbind(last_points, data.frame(
      geo = g,
      country = tail_row$country,
      x = tail_row$year,
      y = tail_row$value,
      color = ts_colors[[g]],
      stringsAsFactors = FALSE
    ))
  }

  # United Kingdom: three decennial census points (dotted line).
  uk_ts$hover <- htxt(sprintf(tr("eu_ts_hover_uk"),
    uk_ts$year_label, fmtv(uk_ts$value)))
  p_ts <- p_ts %>% add_trace(
    data = uk_ts,
    x = ~year, y = ~value,
    type = "scatter", mode = "lines+markers",
    line = list(color = "#4a8c6f", width = 2.5, dash = "dot"),
    marker = list(color = "#4a8c6f", size = 7, symbol = "diamond"),
    text = ~hover,
    hoverinfo = "text",
    showlegend = FALSE,
    legendgroup = "UK"
  )
  last_points <- rbind(last_points, data.frame(
    geo = "UK",
    country = "United Kingdom",
    x = 2021,
    y = 114432,
    color = "#4a8c6f",
    stringsAsFactors = FALSE
  ))

  # France: INSEE annual "immigré" series (dashed, different definition flag).
  fr_ts$hover <- htxt(sprintf(tr("eu_ts_hover_fr"),
    fa_num(fr_ts$year, 0, big = FALSE), fmtv(fr_ts$value)))
  p_ts <- p_ts %>% add_trace(
    data = fr_ts,
    x = ~year, y = ~value,
    type = "scatter", mode = "lines+markers",
    line = list(color = "#8a3a8f", width = 2, dash = "dash"),
    marker = list(color = "#8a3a8f", size = 6, symbol = "square"),
    text = ~hover,
    hoverinfo = "text",
    showlegend = FALSE,
    legendgroup = "FR"
  )
  fr_tail <- tail(fr_ts, 1)
  # France's line ends at 2019, but the label sits near x=2025 alongside the
  # other right-edge labels so the word "France" doesn't get crossed by the
  # NO/IT/DK lines that continue through 2019-2025.
  last_points <- rbind(last_points, data.frame(
    geo = "FR",
    country = "France (2019)",
    x = 2025,
    y = fr_tail$value,
    color = "#8a3a8f",
    stringsAsFactors = FALSE
  ))

  # Switzerland: BFS register (dashed, non-Eurostat source flag).
  ch_ts$hover <- htxt(sprintf(tr("eu_ts_hover_ch"),
    fa_num(ch_ts$year, 0, big = FALSE), fmtv(ch_ts$value)))
  p_ts <- p_ts %>% add_trace(
    data = ch_ts,
    x = ~year, y = ~value,
    type = "scatter", mode = "lines+markers",
    line = list(color = "#3a6a6a", width = 2, dash = "dash"),
    marker = list(color = "#3a6a6a", size = 5, symbol = "triangle-up"),
    text = ~hover,
    hoverinfo = "text",
    showlegend = FALSE,
    legendgroup = "CH"
  )
  ch_tail <- tail(ch_ts, 1)
  last_points <- rbind(last_points, data.frame(
    geo = "CH",
    country = "Switzerland",
    x = ch_tail$year,
    y = ch_tail$value,
    color = "#3a6a6a",
    stringsAsFactors = FALSE
  ))

  # Every label sits in ONE right-aligned column (LABEL_X below), so de-collide
  # them vertically: sort by y and push overlapping labels apart by a gap that
  # scales with the data range (~one label-height regardless of the counts).
  last_points <- last_points[order(last_points$y), ]
  MIN_GAP <- diff(range(last_points$y)) * 0.05
  for (i in seq_len(nrow(last_points))[-1]) {
    if (last_points$y[i] - last_points$y[i - 1] < MIN_GAP) {
      last_points$y[i] <- last_points$y[i - 1] + MIN_GAP
    }
  }

  # All labels align at one x just past the data — a right-hand label column, not
  # per-line-end. This puts a gap between each line's last dot and its label, and
  # lifts the early-ending lines (UK 2021, France 2019) out from under the lines
  # that run to 2025. Colour + vertical position pair each label to its line.
  LABEL_X <- 2025.7
  for (i in seq_len(nrow(last_points))) {
    lp <- last_points[i, ]
    p_ts <- p_ts %>% add_trace(
      x = LABEL_X, y = lp$y,
      text = htxt(paste0(" ", clab(lp$country))),
      type = "scatter",
      mode = "text",
      textposition = "middle right",
      textfont = list(
        color = lp$color,
        size = 12,
        family = "Montserrat"
      ),
      hoverinfo = "skip",
      showlegend = FALSE,
      cliponaxis = FALSE,
      legendgroup = lp$geo
    )
  }

  p_ts <- p_ts %>% layout(
    title = list(text = htxt(sprintf(tr("eu_ts_title"),
        fa_num(1999, 0, big = FALSE), fa_num(2025, 0, big = FALSE))),
      font = list(size = 14, family = "Montserrat")),
    xaxis = list(title = "", tickfont = list(size = 10), dtick = 5,
      # Last TICK is 2025 (every series ends there) — no 2030 tick, no long empty
      # tail. Range reaches a hair past 2025 so the label points (x = LABEL_X,
      # just inside) actually render — plotly culls points outside the range —
      # and cliponaxis = FALSE lets their text spill into the right-margin white
      # space (the wide r below). Next tick (2030) is outside the range, so hidden.
      range = c(1998, 2026)),
    yaxis = list(title = "", tickformat = ",", tickfont = list(size = 10)),
    margin = list(t = 45, b = 30, l = 60, r = 120),
    plot_bgcolor = "white",
    paper_bgcolor = "white",
    showlegend = FALSE,
    hovermode = "closest"
  ) %>% config(displayModeBar = FALSE)

  # Label-hover isolation. The country labels are plotly TEXT-only traces, which
  # carry no hover geometry, so plotly_hover never fires for them (only the lines
  # do). Instead wire a DOM listener on the chart div: match each label's rendered
  # text to its legendgroup and call the highlight_hover helpers (el.__hlOn /
  # el.__hlOff installed by plotly_div(highlight_hover = TRUE)). Delegated on the
  # div so it survives Plotly resizes; the trimmed textContent match ignores the
  # leading space and never matches axis ticks / title.
  ts_disp <- vapply(last_points$country, function(c) trimws(htxt(clab(c))), character(1))
  ts_label_map <- paste0("{", paste(sprintf('"%s":"%s"',
    gsub('"', '\\\\"', ts_disp), last_points$geo), collapse = ","), "}")
  # Label-hover isolation. Plotly sets pointer-events:none on scatter text AND
  # SVG text only hit-tests its glyph ink (gaps miss), so neither a DOM listener
  # on the text nor re-enabling pointer-events is reliable. Instead, after render,
  # drop a solid invisible <div> over each label's bounding box (they sit in the
  # right margin, clear of the plot's drag layer) as a real HTML hover target,
  # matched to its legendgroup, calling the highlight helpers (el.__hlOn/__hlOff
  # from plotly_div(highlight_hover=TRUE)). Rebuilt on resize so it tracks the
  # labels. `M` maps each label's rendered text to its geo/legendgroup.
  ts_hover_js <- sprintf('<script>(function(){var el=document.getElementById("eu-timeseries");if(!el)return;var M=%s;function build(){el.querySelectorAll(".eu-hz").forEach(function(o){o.remove();});if(getComputedStyle(el).position==="static")el.style.position="relative";var er=el.getBoundingClientRect();el.querySelectorAll(".scatterlayer text").forEach(function(t){var g=M[t.textContent.trim()];if(!g)return;var r=t.getBoundingClientRect();if(!r.width)return;var z=document.createElement("div");z.className="eu-hz";z.style.cssText="position:absolute;cursor:pointer;z-index:5;left:"+(r.left-er.left-3)+"px;top:"+(r.top-er.top-2)+"px;width:"+(r.width+6)+"px;height:"+(r.height+4)+"px;";z.addEventListener("mouseenter",function(){if(el.__hlOn)el.__hlOn(g);});z.addEventListener("mouseleave",function(){if(el.__hlOff)el.__hlOff();});el.appendChild(z);});}setTimeout(build,500);window.addEventListener("resize",function(){setTimeout(build,400);});})();</script>', ts_label_map)

  # ---------- ASSEMBLE PAGE -------------------------------------------------
  # Map legend labels (names of the color vector ARE the display labels).
  eu_legend_colors <- c("#9ecae1", "#6baed6", "#2171b5", "#08519c", "#08306b")
  names(eu_legend_colors) <- c(tr("eu_leg_bin1"), tr("eu_leg_bin2"),
    tr("eu_leg_bin3"), tr("eu_leg_bin4"), tr("eu_leg_bin5"))

  body <- paste0(
    # Top row: headline (left) + Europe choropleth map (right)
    '<div class="chart-row">',
    '<div class="headline">',
    '<div class="label">', tr("eu_headline_label"), '</div>',
    '<div class="number">', fmtv(total_iran_born), '</div>',
    '<div class="label" style="margin-top:6px; font-size:13px; color:#555;">',
    sprintf(tr("eu_headline_sublabel"), n_countries), '</div>',
    '<div style="margin:14px auto 0; max-width:440px; font-size:13px; color:#444; text-align:left; line-height:1.7;">',
    '<p style="margin-bottom:6px;">', tr("eu_idbox_intro"), '</p>',
    '<p style="margin:0; font-size:12px; color:#6b6b6b;">', tr("eu_idbox_sources"), '</p>',
    '</div>',
    '</div>',
    '<div class="chart-card">',
    '<div class="section-title" style="margin-top:0;">', tr("eu_map_section_title"), '</div>',
    make_html_legend_hover(eu_legend_colors),
    plotly_div("eu-map", pj(p_map), "430px", source = source_note),
    '</div>',
    '</div>',

    # Bottom row: horizontal bar chart (left) + time series (right)
    '<div class="chart-row">',
    '<div class="chart-card">',
    plotly_div("eu-bar", pj(p_bar), "470px",
      source = paste0(source_note, tr("eu_bar_src_extra"))),
    '</div>',
    '<div class="chart-card">',
    plotly_div("eu-timeseries", pj(p_ts), "460px",
      source = sprintf(tr("eu_ts_src"), EUROSTAT_LINK),
      highlight_hover = TRUE),
    ts_hover_js,
    '</div>',
    '</div>'
  )

  html <- page_template(tr("eu_page_title"), body)
  if (is_fa()) html <- fa_shell(html)
  fname <- if (is_fa()) "docs/pages/eu-overview.fa.html" else "docs/pages/eu-overview.html"
  writeLines(html, fname)
  cat("  Done\n")
}

cat(sprintf("\nEurope overview: %s Iran-born across %d countries.\n",
            format(total_iran_born, big.mark = ","), n_countries))
