# Europe overview page — pan-European Iran-born comparison.
#
# Consumes:
#   data/europe/iran_born_combined.csv  (generated by R/europe_export/build_iran_born_combined.R)
#
# Produces:
#   docs/pages/eu-overview.html
#
# Two charts on one page:
#   1. Bar chart — Iran-born by country, latest available year per country
#   2. Time series — Iran-born trajectory 1998-2025 for countries with
#      continuous Eurostat coverage
#
# Data is harmonized to "Iran-born" (population by country of birth) across
# all sources. Eurostat's migr_pop3ctb table is used for most European
# countries; Germany uses Mikrozensus 2024 because Eurostat doesn't publish
# Iran-born for Germany; UK uses ONS Census 2021 because the UK is not in
# Eurostat's reporting set post-Brexit.
#
# Run from the deployment repo root:
#   Rscript R/build_europe.R

suppressPackageStartupMessages({
  library(plotly)
  library(jsonlite)
  library(dplyr)
})

# Shared helpers: strip_internal_classes(), plotly_to_json(), plotly_div(),
# iframe_resize_script, MAPBOX_ATTRIB_HIDE_CSS.
source("R/_helpers.R")
make_html_legend <- function(colors, labels = names(colors), break_after = NULL) {
  items <- mapply(function(col, lab) {
    html_lab <- gsub("&", "&amp;", lab)
    sprintf('<span data-lg="%s" style="display:inline-flex; align-items:center; gap:4px; cursor:pointer; transition:opacity 0.2s;" onmouseenter="var el=this.closest(\'.chart-card\').querySelector(\'.js-plotly-plot\');if(el&&el.__hlOn)el.__hlOn(this.getAttribute(\'data-lg\'));" onmouseleave="var el=this.closest(\'.chart-card\').querySelector(\'.js-plotly-plot\');if(el&&el.__hlOff)el.__hlOff();"><span style="width:12px; height:12px; background:%s; border-radius:2px; display:inline-block;"></span> %s</span>',
      lab, col, html_lab)
  }, colors, labels, SIMPLIFY = TRUE)
  sprintf('<div style="display:flex; justify-content:center; flex-wrap:wrap; gap:6px 14px; font-size:12px; color:#444; margin:6px 0 2px; line-height:2;">%s</div>',
    paste(items, collapse = ""))
}

page_template <- function(title, body_html, extra_head = "") {
  paste0('<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>', title, '</title>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&display=swap" rel="stylesheet">
<script src="lib/plotly-3.4.0.min.js"></script>
<style>
* { margin:0; padding:0; box-sizing:border-box; }
body { font-family:"Montserrat",sans-serif; background:#fafafa; color:#333; padding:15px 40px; max-width:100%; overflow-x:hidden; }
.text-row { display:grid; grid-template-columns:1fr 1fr; gap:20px; margin-bottom:20px; }
.text-card { background:white; border-radius:8px; padding:20px; text-align:center;
  font-size:15px; line-height:1.6; border:1px solid #e0e0e0; }
.chart-row { display:grid; grid-template-columns:1fr 1fr; gap:20px; margin-bottom:20px; align-items:stretch; }
.chart-card { background:white; border-radius:8px; padding:16px; border:1px solid #e0e0e0; margin-bottom:20px; overflow:hidden; min-width:0; }
.section-title { font-size:16px; font-weight:600; text-align:center; margin:16px 0 8px; }
.headline { background:white; border-radius:8px; padding:30px; text-align:center; border:1px solid #e0e0e0; margin-bottom:20px; }
.headline .number { font-size:44px; font-weight:700; color:#1a4e72; line-height:1.1; letter-spacing:-0.02em; }
a { transition: color 0.15s; }
a:hover { color: #1a4e72 !important; text-decoration: underline; }
.headline .label { font-size:14px; color:#666; margin-top:6px; }
@media (max-width:900px) {
  body { padding:10px 15px; }
  .text-row, .chart-row { grid-template-columns:1fr !important; }
  .headline .number { font-size:34px; }
  .headline { padding:20px 15px; }
  .section-title { font-size:14px; }
}
@media (max-width:480px) {
  body { padding:8px 10px; }
  .text-card { font-size:13px; padding:14px; }
  .headline .number { font-size:28px; }
  .chart-card { padding:10px; }
}
', MAPBOX_ATTRIB_HIDE_CSS, '
</style>
', extra_head, '
</head>
<body>
', body_html, '
', iframe_resize_script, '
</body>
</html>')
}

# ---------- DATA ----------------------------------------------------------
cat("Building Europe overview page...\n")

combined <- read.csv("data/europe/iran_born_combined.csv", stringsAsFactors = FALSE)

# ISO-3 codes for plotly's built-in country boundaries
iso3_map <- c(
  AT = "AUT", BE = "BEL", CH = "CHE", DE = "DEU", DK = "DNK",
  ES = "ESP", FI = "FIN", FR = "FRA", IT = "ITA", NL = "NLD",
  NO = "NOR", SE = "SWE", UK = "GBR"
)

# Latest year per country
latest <- combined %>%
  group_by(geo, country) %>%
  slice_max(year, n = 1) %>%
  ungroup() %>%
  arrange(desc(value)) %>%
  mutate(iso3 = iso3_map[geo])

total_iran_born <- sum(latest$value)

# ---------- CHART 1: Europe choropleth map (top-right) -------------------
# Uses plotly's built-in country boundaries — no GeoJSON needed.
# scope="europe" auto-frames the viewport to Europe. Discrete bins avoid
# plotly_build's continuous-colorscale zcolor serialization issue.
latest$map_bin <- cut(latest$value,
  breaks = c(0, 20000, 35000, 70000, 120000, Inf),
  labels = 1:5, include.lowest = TRUE) %>% as.integer()
bin_labels <- c(
  "1" = "Under 20,000",
  "2" = "20,000 – 35,000",
  "3" = "35,000 – 70,000",
  "4" = "70,000 – 120,000",
  "5" = "120,000 or more"
)
bin_colors <- list(
  c(0,   "#c6dbef"),
  c(0.2, "#9ecae1"),
  c(0.4, "#6baed6"),
  c(0.6, "#2171b5"),
  c(0.8, "#08519c"),
  c(1.0, "#08306b")
)

p_map <- plot_ly(type = "choropleth",
    locations = latest$iso3,
    z = latest$map_bin,
    text = sprintf("<b>%s</b><br>%s Iran-born residents<br>Most recent year: %d",
      latest$country, format(latest$value, big.mark = ","), latest$year),
    hoverinfo = "text",
    colorscale = bin_colors,
    zmin = 0, zmax = 5,
    showscale = FALSE,
    marker = list(line = list(color = "white", width = 0.8))
  ) %>%
  layout(
    geo = list(
      scope = "europe",
      showframe = FALSE,
      showcoastlines = TRUE,
      coastlinecolor = "#d0d0d0",
      projection = list(type = "mercator"),
      bgcolor = "white",
      landcolor = "#f5f5f5",
      showland = TRUE,
      showcountries = TRUE,
      countrycolor = "#d0d0d0",
      lataxis = list(range = c(34, 74)),
      lonaxis = list(range = c(-13, 33))
    ),
    margin = list(t = 5, b = 5, l = 0, r = 0),
    paper_bgcolor = "white"
  ) %>%
  config(displayModeBar = FALSE)

# ---------- CHART 3: Horizontal bar chart (bottom-right) -----------------
# Smaller, horizontal orientation so country names read cleanly.
# Reverse factor order so largest value is on top of the chart.
bar_df <- latest %>% arrange(value)
bar_df$country <- factor(bar_df$country, levels = bar_df$country)

p_bar <- plot_ly(
    bar_df,
    y = ~country,
    x = ~value,
    type = "bar",
    orientation = "h",
    marker = list(color = "#2774AE",
                  line = list(color = "#1a4e72", width = 0.4)),
    text = ~sprintf("<b>%s</b><br>%s Iran-born (%d)",
      country, format(value, big.mark = ","), year),
    hoverinfo = "text",
    textposition = "none"
  ) %>%
  layout(
    title = list(text = "<b>Iran-Born in Europe by Country,<br>Most Recent Year</b>",
      font = list(size = 14, family = "Montserrat")),
    xaxis = list(title = "", tickformat = ",", tickfont = list(size = 10)),
    yaxis = list(title = "", tickfont = list(size = 11),
                 ticks = "outside", ticklen = 8,
                 tickcolor = "rgba(0,0,0,0)"),
    margin = list(t = 45, b = 30, l = 120, r = 20),
    plot_bgcolor = "white",
    paper_bgcolor = "white",
    showlegend = FALSE,
    bargap = 0.35
  ) %>%
  config(displayModeBar = FALSE)

# ---------- CHART 2: Time series (countries with continuous coverage) ----
# Show the Eurostat-continuous countries plus Finland. Finland's 2025
# count (~15K) is below the top-6 cutoff by value but has 25 years of
# coverage; it sits visibly below DK and rounds out the seven-country
# Eurostat panel.
coverage <- combined %>%
  group_by(geo, country) %>%
  summarise(n = n(), .groups = "drop")

eurostat_only <- latest %>%
  filter(!geo %in% c("DE", "UK", "FR", "CH", "BE")) %>%
  left_join(coverage, by = c("geo", "country")) %>%
  filter(n >= 15) %>%
  arrange(desc(value))

top_eurostat <- head(eurostat_only, 7)
ts_data <- combined %>% filter(geo %in% top_eurostat$geo)

# Colour each country with a distinct but complementary hue; the seven
# Eurostat-continuous countries are SE, NL, AT, IT, NO, DK, FI.
ts_colors <- c(
  "SE" = "#1a4e72",   # Sweden — dark blue
  "NL" = "#c4793a",   # Netherlands — orange
  "AT" = "#4a8c6f",   # Austria — green
  "IT" = "#8a3a8f",   # Italy — purple
  "NO" = "#5a9bd5",   # Norway — light blue
  "DK" = "#b05050",   # Denmark — muted red
  "FI" = "#d4a943"    # Finland — gold
)

# Direct-label each line at its rightmost point instead of using a legend —
# standard line-chart practice (see ggplot2-4.md in the r-coding skill).
# Build the line traces first, then a single text trace for the labels.
p_ts <- plot_ly()
last_points <- data.frame(
  geo = character(), country = character(),
  x = integer(), y = integer(), color = character(),
  stringsAsFactors = FALSE
)
for (g in top_eurostat$geo) {
  d <- ts_data %>% filter(geo == g) %>% arrange(year)
  p_ts <- p_ts %>% add_trace(
    data = d,
    x = ~year, y = ~value,
    type = "scatter", mode = "lines+markers",
    line = list(color = ts_colors[[g]], width = 2.5),
    marker = list(color = ts_colors[[g]], size = 5),
    text = ~sprintf("<b>%s</b> %d<br>%s Iran-born residents",
      country, year, format(value, big.mark = ",")),
    hoverinfo = "text",
    showlegend = FALSE,
    legendgroup = g
  )
  tail_row <- tail(d, 1)
  last_points <- rbind(last_points, data.frame(
    geo = g,
    country = tail_row$country,
    x = tail_row$year,
    y = tail_row$value,
    color = ts_colors[[g]],
    stringsAsFactors = FALSE
  ))
}

# United Kingdom: three decennial census points (2001, 2011, 2021/22). Sources:
#   2001 Census: ~42,500 Iran-born in England and Wales (ONS)
#   2011 Census:  84,735 UK total (79,985 E + 1,695 W + 2,773 S + 282 NI)
#   2021 Census: 114,432 UK total (E+W 2021 ONS + NI 2021 NISRA + Scotland 2022 NRS)
# Note: the 2021 point is labeled 2021/22 because the Scottish census was
# run a year later; the other two constituent nations are 2021.
uk_ts <- data.frame(
  year = c(2001, 2011, 2021),
  year_label = c("2001", "2011", "2021/22"),
  value = c(42494, 84735, 114432),
  country = "United Kingdom",
  stringsAsFactors = FALSE
)
p_ts <- p_ts %>% add_trace(
  data = uk_ts,
  x = ~year, y = ~value,
  type = "scatter", mode = "lines+markers",
  line = list(color = "#4a8c6f", width = 2.5, dash = "dot"),
  marker = list(color = "#4a8c6f", size = 7, symbol = "diamond"),
  text = ~sprintf("<b>United Kingdom</b> %s<br>%s Iran-born residents (census)",
    year_label, format(value, big.mark = ",")),
  hoverinfo = "text",
  showlegend = FALSE,
  legendgroup = "UK"
)
last_points <- rbind(last_points, data.frame(
  geo = "UK",
  country = "United Kingdom",
  x = 2021,
  y = 114432,
  color = "#4a8c6f",
  stringsAsFactors = FALSE
))

# France: INSEE annual "immigré" series, 2006-2019 (2018 not published).
# Drawn as a dashed line to flag the different definition vs Eurostat — same
# visual convention as the UK line, different dash style and marker symbol.
fr_ts <- combined %>% filter(geo == "FR", year >= 1999) %>% arrange(year)
p_ts <- p_ts %>% add_trace(
  data = fr_ts,
  x = ~year, y = ~value,
  type = "scatter", mode = "lines+markers",
  line = list(color = "#8a3a8f", width = 2, dash = "dash"),
  marker = list(color = "#8a3a8f", size = 6, symbol = "square"),
  text = ~sprintf("<b>France</b> %d<br>%s Iran-born (INSEE immigr\u00e9 definition)",
    year, format(value, big.mark = ",")),
  hoverinfo = "text",
  showlegend = FALSE,
  legendgroup = "FR"
)
fr_tail <- tail(fr_ts, 1)
# France's line ends at 2019, but the label sits near x=2025 alongside the other
# right-edge labels so the word "France" doesn't get crossed by the NO/IT/DK
# lines that continue through 2019-2025.
last_points <- rbind(last_points, data.frame(
  geo = "FR",
  country = "France (2019)",
  x = 2025,
  y = fr_tail$value,
  color = "#8a3a8f",
  stringsAsFactors = FALSE
))

# Switzerland: BFS register, 2010-2024 (continuous, but not Eurostat —
# show dashed alongside UK/FR to flag the non-Eurostat source).
ch_ts <- combined %>% filter(geo == "CH") %>% arrange(year)
p_ts <- p_ts %>% add_trace(
  data = ch_ts,
  x = ~year, y = ~value,
  type = "scatter", mode = "lines+markers",
  line = list(color = "#3a6a6a", width = 2, dash = "dash"),
  marker = list(color = "#3a6a6a", size = 5, symbol = "triangle-up"),
  text = ~sprintf("<b>Switzerland</b> %d<br>%s Iran-born",
    year, format(value, big.mark = ",")),
  hoverinfo = "text",
  showlegend = FALSE,
  legendgroup = "CH"
)
ch_tail <- tail(ch_ts, 1)
last_points <- rbind(last_points, data.frame(
  geo = "CH",
  country = "Switzerland",
  x = ch_tail$year,
  y = ch_tail$value,
  color = "#3a6a6a",
  stringsAsFactors = FALSE
))

# The Netherlands / Austria lines land close together at the right edge.
# Nudge overlapping labels vertically so they don't collide. Sort by y and
# bump any label that is within MIN_GAP of the previous one.
last_points <- last_points[order(last_points$y), ]
MIN_GAP <- 3500
for (i in seq_len(nrow(last_points))[-1]) {
  gap <- last_points$y[i] - last_points$y[i - 1]
  if (gap < MIN_GAP) {
    last_points$y[i] <- last_points$y[i - 1] + MIN_GAP
  }
}

# Build one text trace per country so each label can be paired with its
# line via legendgroup. This lets the hover handler dim the OTHER labels
# while leaving the hovered line and its label at full opacity.
for (i in seq_len(nrow(last_points))) {
  lp <- last_points[i, ]
  p_ts <- p_ts %>% add_trace(
    x = lp$x, y = lp$y,
    text = paste0(" ", lp$country),
    type = "scatter",
    mode = "text",
    textposition = "middle right",
    textfont = list(
      color = lp$color,
      size = 12,
      family = "Montserrat"
    ),
    hoverinfo = "skip",
    showlegend = FALSE,
    cliponaxis = FALSE,
    legendgroup = lp$geo
  )
}

p_ts <- p_ts %>% layout(
  title = list(text = "<b>Iran-Born Population in Europe<br>Over Time, 1999\u20132025</b>",
    font = list(size = 14, family = "Montserrat")),
  xaxis = list(title = "", tickfont = list(size = 10), dtick = 5,
    # Range starts at 1998 \u2014 earliest year any series in the chart has
    # data (France 1999 census, Sweden/Eurostat from 1999). Extends past
    # 2025 so the right-edge country labels render without clipping.
    range = c(1998, 2033)),
  yaxis = list(title = "", tickformat = ",", tickfont = list(size = 10)),
  margin = list(t = 45, b = 30, l = 60, r = 15),
  plot_bgcolor = "white",
  paper_bgcolor = "white",
  showlegend = FALSE,
  hovermode = "closest"
) %>% config(displayModeBar = FALSE)

# ---------- ASSEMBLE PAGE -------------------------------------------------
EUROSTAT_LINK <- "<a href='https://ec.europa.eu/eurostat/databrowser/view/migr_pop3ctb/default/table' target='_blank' style='color:#2774AE;'>Eurostat</a>"
MIKRO_LINK <- "<a href='https://www.destatis.de/DE/Themen/Gesellschaft-Umwelt/Bevoelkerung/Migration-Integration/Publikationen/Downloads-Migration/statistischer-bericht-migrationshintergrund-erst-2010220247005.html' target='_blank' style='color:#2774AE;'>Destatis Mikrozensus 2024</a>"
ONS_LINK <- "<a href='https://www.nomisweb.co.uk/sources/census_2021' target='_blank' style='color:#2774AE;'>ONS Census 2021</a>"
NRS_LINK <- "<a href='https://www.scotlandscensus.gov.uk/' target='_blank' style='color:#2774AE;'>NRS Scotland's Census 2022</a>"
NISRA_LINK <- "<a href='https://www.nisra.gov.uk/statistics/census/2021-census' target='_blank' style='color:#2774AE;'>NISRA NI Census 2021</a>"
BFS_LINK <- "<a href='https://www.bfs.admin.ch/bfs/en/home/statistics/population.html' target='_blank' style='color:#2774AE;'>Swiss Federal Statistical Office (BFS)</a>"
UK_COMBINED_LINK <- paste0(ONS_LINK, " (England &amp; Wales), ", NRS_LINK, ", and ", NISRA_LINK)

source_note <- sprintf(
  "Source: %s population by country of birth. Germany from %s. United Kingdom combined from %s.",
  EUROSTAT_LINK, MIKRO_LINK, UK_COMBINED_LINK)

n_countries <- nrow(latest)

body <- paste0(
  # Top row: headline (left) + Europe choropleth map (right)
  '<div class="chart-row">',
  '<div class="headline">',
  '<div class="label">Estimated Iran-Born Population in Europe</div>',
  '<div class="number">', format(total_iran_born, big.mark = ","), '</div>',
  '<div class="label" style="margin-top:6px; font-size:13px; color:#555;">Summed across ', n_countries, ' European countries with published data</div>',
  '<div style="margin:14px auto 0; max-width:440px; font-size:13px; color:#444; text-align:left; line-height:1.7;">',
  '<p style="margin-bottom:8px;">A person is counted if they were born in Iran and currently live in one of:</p>',
  '<ul style="padding-left:20px; margin:0; line-height:2;">',
  '<li><strong>', EUROSTAT_LINK, '</strong> <span style="color:#888;">&mdash; 8 European countries (country-of-birth tables)</span></li>',
  '<li><strong>', MIKRO_LINK, '</strong> <span style="color:#888;">&mdash; Germany</span></li>',
  '<li><strong>', ONS_LINK, ', ', NRS_LINK, ', ', NISRA_LINK, '</strong> <span style="color:#888;">&mdash; United Kingdom (combined)</span></li>',
  '<li><strong>', BFS_LINK, '</strong> <span style="color:#888;">&mdash; Switzerland (STATPOP register)</span></li>',
  '</ul>',
  '</div>',
  '</div>',
  '<div class="chart-card">',
  '<div class="section-title" style="margin-top:0;">Where Iran-Born Residents Live in Europe</div>',
  make_html_legend(c(
    "Under 20,000" = "#9ecae1",
    "20,000 \u2013 35,000" = "#6baed6",
    "35,000 \u2013 70,000" = "#2171b5",
    "70,000 \u2013 120,000" = "#08519c",
    "120,000 or more" = "#08306b"
  )),
  plotly_div("eu-map", plotly_to_json(p_map), "430px", source = source_note),
  '</div>',
  '</div>',

  # Bottom row: horizontal bar chart (left) + time series (right)
  '<div class="chart-row">',
  '<div class="chart-card">',
  plotly_div("eu-bar", plotly_to_json(p_bar), "460px",
    source = source_note),
  '</div>',
  '<div class="chart-card">',
  plotly_div("eu-timeseries", plotly_to_json(p_ts), "460px",
    source = paste0("Source: ", EUROSTAT_LINK, " for the seven solid lines (Sweden, Netherlands, Austria, Italy, Norway, Denmark, Finland). United Kingdom (dotted) is from ONS/NRS/NISRA census points 2001, 2011, and 2021/22. France (dashed) is from INSEE Recensement de la population \u2014 census snapshot 1999, then continuous 2006\u20132019. The INSEE \u201Cimmigr\u00e9\u201D definition is narrower than Eurostat\u2019s foreign-born. Switzerland (dashed) is from the BFS register, 2010\u20132024. Germany is omitted because Eurostat does not publish Iran-born counts for Germany; see the Germany pages."),
    highlight_hover = TRUE),
  '</div>',
  '</div>'
)

dir.create("docs/pages", showWarnings = FALSE, recursive = TRUE)
writeLines(page_template("Europe: Iran-Born Overview", body), "docs/pages/eu-overview.html")
cat("  Done\n")
cat(sprintf("\nEurope overview: %s Iran-born across %d countries.\n",
            format(total_iran_born, big.mark = ","), n_countries))
